trigger:
  branches:
    exclude:
      - '*'

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true

- script: pip install tkinter
  displayName: 'Install dependencies'

- script: pyinstaller --onefile your_tkinter_app.py
  displayName: 'Build Tkinter app'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: 'dist'
    artifactName: 'TkinterApp'
